# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Website name (set in params.yaml under hugoblox.branding.name)
title: 'Jiannan Zhang'
# Website URL
baseURL: 'https://www.zhangjn.xyz/'

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: true
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## PAGE OPTIONS
############################

cascade:
  - target:
      path: /slides/**
      kind: page
    outputs: [HTML, present]
  - target:
      path: /publications/**
    profile: false
    share: false
    reading_time: false  # 隐藏文献副标题栏的阅读时间

  - target:
      path: /blog/**
    profile: false
    share: false
    toc: true     # 强制为所有博客文章开启大纲目录
  - target:
      path: /projects/**
    profile: false
    share: false
  - target:
      path: /courses/**
    type: book   # 强制将 courses 目录下的所有页面以书本/文档的样式渲染



    
############################
## ADVANCED
############################

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 50
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
disableAliases: true
outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart
  hint: picture
timeout: 600000
taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types
markup:
  _merge: deep
  highlight:
    lineNos: true
  goldmark:
    renderer:
      unsafe: true
security:
  _merge: deep
sitemap:
  _merge: deep
